name: Bug report
description: Create a bug report to help us improve
title: "<title>"
labels: bug
body:
- type: markdown
  attributes:
    value: "## Thank you for contributing to this project!"
- type: checkboxes
  attributes:
    label: Please check these items before go any further
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have watched [Mr. Green theme tutorials playlist](https://www.youtube.com/playlist?list=PLAymxPbYHgl-fFy5can7uZBMJtFWVcphD) on YouTube.
      required: true
    - label: I have searched the existing [Issues](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/issues/).
      required: true
    - label: I have searched the existing [Discussions](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/discussions/).
      required: true
    - label: I have checked [jekyll docs](https://jekyllrb.com/docs/) and the answer was not there.
      required: true
    - label: I have tested in one of these browsers; Safari, Chrome, Firefox. (This project hasn't been tested in other browsers.)
      required: true
- type: checkboxes
  attributes:
    label: Are you sure this is a bug?
    description: |
      The Issues in this repo is only used for 'Bug reports' or 'Feature requests'.
      If you are not sure if this is a bug or not, please ask a question from [Discussions](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/issues/new?assignees=&labels=delete+me&template=a_questions.yml&title=%3Ctitle%3E).
    options:
    - label: I'm sure this is definitely a bug.
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      A clear and concise description of what the bug is.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    #value: |
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Which browser have you used?
    description: You may select more than one.
    options:
    - label: Chrome
      required: false
    - label: Safari
      required: false
    - label: Firefox
      required: false
    - label: Other browsers (This project hasn't been tested in other browsers.)
- type: checkboxes
  attributes:
    label: Which device have you used?
    description: You may select more than one.
    options:
    - label: Desktop
      required: false
    - label: Mobile IOS
      required: false
    - label: Mobile Android
      required: false
    - label: Other platforms (This project hasn't been tested in other devices.)
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this bug report.
